\documentclass[a4paper,11pt]{jsarticle}
\usepackage[margin=20truemm]{geometry}	% 余白の設定
\usepackage[dvipdfmx]{graphicx}		% 図を読み込む際に必要
\usepackage{url}			% \url コマンド用
\usepackage{amsmath}			% 数式用
\usepackage{listings}			% プログラムリスト用
\usepackage{color}

\lstset{
  language=C,
  basicstyle={\ttfamily\footnotesize},
  commentstyle=\textit,
  classoffset=1,
  keywordstyle=\bfseries,
  frame=tRBl,framesep=5pt,
  showstringspaces=false,
  numbers=left,
  stepnumber=1,
  numberstyle={\ttfamily\footnotesize},
  breaklines=true,
  breakindent = 10pt,
  tabsize=4,
  columns=fixed,
  basewidth=0.5em,
}

\title{レポートタイトル}
\author{学生番号 氏名}
\date{\today}

\begin{document}

\maketitle

\section{目的}
ここにレポートの目的を記述します。

\section{方法}
ここに実験や実装の方法を記述します。

\section{結果}
ここに結果を記述し、図や表を適宜挿入します。

\section{考察}
結果に対する考察を記述します。

% 参考文献
\begin{thebibliography}{9}
  %
  %
  \bibitem{参照キー1}
    著者名リスト, ``タイトル,'' in \textit{Proceedings of 会議名}, pp.開始ページ--終了ページ, 年. DOI: DOI があれば記述
  \bibitem{参照キー2}
    ``Webページタイトル,''
    \url{https://aaa.com/bbb/ccc.html},
    accessed Jul. 21, 2025.
\end{thebibliography}

\end{document}
